import { integer, pgTable, text, timestamp, uniqueIndex, varchar } from 'drizzle-orm/pg-core';

/**
 * User table.
 *
 * id is a UUID v4 generated at insert time via crypto.randomUUID().
 * This runs server-side (Node.js via Expo API Routes), not in the
 * React Native runtime, so crypto.randomUUID() is available.
 *
 * updatedAt does not use $onUpdate because the neon-http driver does
 * not support driver-level update hooks. Callers must set updatedAt
 * explicitly on UPDATE queries.
 *
 * Game stats (xp, coins, level) default to 0 / 1 for new users.
 */
export const users = pgTable('users', {
  id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
  email: varchar('email', { length: 255 }).notNull().unique(),
  name: varchar('name', { length: 255 }),
  avatarUrl: text('avatar_url'),
  xp: integer('xp').default(0).notNull(),
  coins: integer('coins').default(0).notNull(),
  level: integer('level').default(1).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

/** Full user row as returned by SELECT. */
export type User = typeof users.$inferSelect;

/** Shape for inserting a new user (columns with defaults are optional). */
export type NewUser = typeof users.$inferInsert;

/**
 * Courses table — AI-generated learning courses.
 *
 * Stores course requests created by users.
 * - title: derived from the user's description
 * - description: the raw user input describing what they want to learn
 * - icon: emoji icon generated by AI
 * - difficulty: 'beginner' | 'intermediate' | 'advanced'
 * - status: 'draft' → 'generating' → 'ready' (or 'failed')
 */
export const courses = pgTable('courses', {
  id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
  userId: varchar('user_id', { length: 36 }).notNull().references(() => users.id),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description').notNull(),
  icon: varchar('icon', { length: 10 }),
  difficulty: varchar('difficulty', { length: 20 }).notNull().default('beginner'),
  status: varchar('status', { length: 20 }).notNull().default('draft'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

/** Full course row as returned by SELECT. */
export type Course = typeof courses.$inferSelect;

/** Shape for inserting a new course. */
export type NewCourse = typeof courses.$inferInsert;

/**
 * Chapters table — a chapter belongs to a course.
 *
 * Each chapter contains multiple lessons. Chapters are ordered
 * by the `order` column within a course.
 */
export const chapters = pgTable('chapters', {
  id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
  courseId: varchar('course_id', { length: 36 }).notNull().references(() => courses.id),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description'),
  order: integer('order').notNull().default(0),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

/** Full chapter row as returned by SELECT. */
export type Chapter = typeof chapters.$inferSelect;

/** Shape for inserting a new chapter. */
export type NewChapter = typeof chapters.$inferInsert;

/**
 * Lessons table — a lesson belongs to a chapter.
 *
 * Each lesson contains the actual teaching content in Markdown format.
 * Lessons are ordered by the `order` column within a chapter.
 */
export const lessons = pgTable('lessons', {
  id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
  chapterId: varchar('chapter_id', { length: 36 }).notNull().references(() => chapters.id),
  title: varchar('title', { length: 255 }).notNull(),
  content: text('content').notNull(),
  order: integer('order').notNull().default(0),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

/** Full lesson row as returned by SELECT. */
export type Lesson = typeof lessons.$inferSelect;

/** Shape for inserting a new lesson. */
export type NewLesson = typeof lessons.$inferInsert;

/**
 * Lesson completions table — one row per completed lesson per user.
 *
 * The unique index on (userId, lessonId) prevents duplicate rewards:
 * completing a lesson twice never grants XP/coins a second time.
 */
export const lessonCompletions = pgTable(
  'lesson_completions',
  {
    id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: varchar('user_id', { length: 36 }).notNull().references(() => users.id),
    lessonId: varchar('lesson_id', { length: 36 }).notNull().references(() => lessons.id),
    xpEarned: integer('xp_earned').notNull().default(0),
    coinsEarned: integer('coins_earned').notNull().default(0),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (t) => [uniqueIndex('lesson_completions_user_lesson_idx').on(t.userId, t.lessonId)],
);

/** Full lesson completion row as returned by SELECT. */
export type LessonCompletion = typeof lessonCompletions.$inferSelect;

/** Shape for inserting a new lesson completion. */
export type NewLessonCompletion = typeof lessonCompletions.$inferInsert;

/**
 * Bounty completions table — daily bounty claims.
 *
 * `day` is a 'YYYY-MM-DD' string (server-local date). The unique index on
 * (userId, bountyKey, day) means each bounty can only be claimed once per day.
 */
export const bountyCompletions = pgTable(
  'bounty_completions',
  {
    id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: varchar('user_id', { length: 36 }).notNull().references(() => users.id),
    bountyKey: varchar('bounty_key', { length: 50 }).notNull(),
    day: varchar('day', { length: 10 }).notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (t) => [uniqueIndex('bounty_completions_user_bounty_day_idx').on(t.userId, t.bountyKey, t.day)],
);

/** Full bounty completion row as returned by SELECT. */
export type BountyCompletion = typeof bountyCompletions.$inferSelect;

/** Shape for inserting a new bounty completion. */
export type NewBountyCompletion = typeof bountyCompletions.$inferInsert;

/**
 * User achievements table — one row per unlocked achievement per user.
 *
 * The unique index on (userId, achievementKey) means each achievement can
 * only be unlocked once.
 */
export const userAchievements = pgTable(
  'user_achievements',
  {
    id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: varchar('user_id', { length: 36 }).notNull().references(() => users.id),
    achievementKey: varchar('achievement_key', { length: 50 }).notNull(),
    unlockedAt: timestamp('unlocked_at').defaultNow().notNull(),
  },
  (t) => [uniqueIndex('user_achievements_user_key_idx').on(t.userId, t.achievementKey)],
);

/** Full user achievement row as returned by SELECT. */
export type UserAchievement = typeof userAchievements.$inferSelect;

/** Shape for inserting a new user achievement. */
export type NewUserAchievement = typeof userAchievements.$inferInsert;
